// Mocks generated by Mockito 5.3.0 from annotations
// in ditonton/test/presentation/pages/tv_detail_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;
import 'dart:ui' as _i14;

import 'package:ditonton/common/state_enum.dart' as _i11;
import 'package:ditonton/domain/entities/tv.dart' as _i12;
import 'package:ditonton/domain/entities/tv_detail.dart' as _i7;
import 'package:ditonton/domain/entities/tv_seasons_detail.dart' as _i9;
import 'package:ditonton/domain/usecases/get_tv_detail.dart' as _i2;
import 'package:ditonton/domain/usecases/get_tv_recommendations.dart' as _i3;
import 'package:ditonton/domain/usecases/get_tv_season_detail.dart' as _i8;
import 'package:ditonton/domain/usecases/get_watchlist_status_tv.dart' as _i4;
import 'package:ditonton/domain/usecases/remove_watchlist_tv.dart' as _i6;
import 'package:ditonton/domain/usecases/save_watchlist_tv.dart' as _i5;
import 'package:ditonton/presentation/provider/tv_detail_notifier.dart' as _i10;
import 'package:ditonton/presentation/provider/tv_season_detail_notifier.dart'
    as _i15;
import 'package:flutter/material.dart' as _i16;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetTVDetail_0 extends _i1.SmartFake implements _i2.GetTVDetail {
  _FakeGetTVDetail_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeGetTVRecommendations_1 extends _i1.SmartFake
    implements _i3.GetTVRecommendations {
  _FakeGetTVRecommendations_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeGetWatchListStatusTV_2 extends _i1.SmartFake
    implements _i4.GetWatchListStatusTV {
  _FakeGetWatchListStatusTV_2(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeSaveWatchlistTV_3 extends _i1.SmartFake
    implements _i5.SaveWatchlistTV {
  _FakeSaveWatchlistTV_3(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeRemoveWatchlistTV_4 extends _i1.SmartFake
    implements _i6.RemoveWatchlistTV {
  _FakeRemoveWatchlistTV_4(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeTVDetail_5 extends _i1.SmartFake implements _i7.TVDetail {
  _FakeTVDetail_5(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeGetTVSeasonDetail_6 extends _i1.SmartFake
    implements _i8.GetTVSeasonDetail {
  _FakeGetTVSeasonDetail_6(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeTVSeasons_7 extends _i1.SmartFake implements _i9.TVSeasonsDetail {
  _FakeTVSeasons_7(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [TVDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVDetailNotifier extends _i1.Mock implements _i10.TVDetailNotifier {
  MockTVDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTVDetail get getTVDetail =>
      (super.noSuchMethod(Invocation.getter(#getTVDetail),
              returnValue:
                  _FakeGetTVDetail_0(this, Invocation.getter(#getTVDetail)))
          as _i2.GetTVDetail);
  @override
  _i3.GetTVRecommendations get getTVRecommendations =>
      (super.noSuchMethod(Invocation.getter(#getTVRecommendations),
              returnValue: _FakeGetTVRecommendations_1(
                  this, Invocation.getter(#getTVRecommendations)))
          as _i3.GetTVRecommendations);
  @override
  _i4.GetWatchListStatusTV get getWatchListStatus =>
      (super.noSuchMethod(Invocation.getter(#getWatchListStatus),
              returnValue: _FakeGetWatchListStatusTV_2(
                  this, Invocation.getter(#getWatchListStatus)))
          as _i4.GetWatchListStatusTV);
  @override
  _i5.SaveWatchlistTV get saveWatchlist => (super.noSuchMethod(
          Invocation.getter(#saveWatchlist),
          returnValue:
              _FakeSaveWatchlistTV_3(this, Invocation.getter(#saveWatchlist)))
      as _i5.SaveWatchlistTV);
  @override
  _i6.RemoveWatchlistTV get removeWatchlist => (super.noSuchMethod(
      Invocation.getter(#removeWatchlist),
      returnValue: _FakeRemoveWatchlistTV_4(
          this, Invocation.getter(#removeWatchlist))) as _i6.RemoveWatchlistTV);
  @override
  _i7.TVDetail get tvDetail => (super.noSuchMethod(Invocation.getter(#tvDetail),
          returnValue: _FakeTVDetail_5(this, Invocation.getter(#tvDetail)))
      as _i7.TVDetail);
  @override
  _i11.RequestState get tvDetailState =>
      (super.noSuchMethod(Invocation.getter(#tvDetailState),
          returnValue: _i11.RequestState.Empty) as _i11.RequestState);
  @override
  List<_i12.TV> get tvRecommendations =>
      (super.noSuchMethod(Invocation.getter(#tvRecommendations),
          returnValue: <_i12.TV>[]) as List<_i12.TV>);
  @override
  _i11.RequestState get tvRecommendationsState =>
      (super.noSuchMethod(Invocation.getter(#tvRecommendationsState),
          returnValue: _i11.RequestState.Empty) as _i11.RequestState);
  @override
  String get message =>
      (super.noSuchMethod(Invocation.getter(#message), returnValue: '')
          as String);
  @override
  bool get isAddedToWatchlist =>
      (super.noSuchMethod(Invocation.getter(#isAddedToWatchlist),
          returnValue: false) as bool);
  @override
  String get watchlistMessage =>
      (super.noSuchMethod(Invocation.getter(#watchlistMessage), returnValue: '')
          as String);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  _i13.Future<void> fetchTVDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#fetchTVDetail, [id]),
              returnValue: _i13.Future<void>.value(),
              returnValueForMissingStub: _i13.Future<void>.value())
          as _i13.Future<void>);
  @override
  _i13.Future<void> addWatchlist(_i7.TVDetail? tv) =>
      (super.noSuchMethod(Invocation.method(#addWatchlist, [tv]),
              returnValue: _i13.Future<void>.value(),
              returnValueForMissingStub: _i13.Future<void>.value())
          as _i13.Future<void>);
  @override
  _i13.Future<void> removeFromWatchlist(_i7.TVDetail? tv) =>
      (super.noSuchMethod(Invocation.method(#removeFromWatchlist, [tv]),
              returnValue: _i13.Future<void>.value(),
              returnValueForMissingStub: _i13.Future<void>.value())
          as _i13.Future<void>);
  @override
  _i13.Future<void> loadWatchlistStatus(int? id) =>
      (super.noSuchMethod(Invocation.method(#loadWatchlistStatus, [id]),
              returnValue: _i13.Future<void>.value(),
              returnValueForMissingStub: _i13.Future<void>.value())
          as _i13.Future<void>);
  @override
  void addListener(_i14.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i14.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}

/// A class which mocks [TVSeasonDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVSeasonDetailNotifier extends _i1.Mock
    implements _i15.TVSeasonDetailNotifier {
  MockTVSeasonDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.GetTVSeasonDetail get getTVSeasonDetail =>
      (super.noSuchMethod(Invocation.getter(#getTVSeasonDetail),
              returnValue: _FakeGetTVSeasonDetail_6(
                  this, Invocation.getter(#getTVSeasonDetail)))
          as _i8.GetTVSeasonDetail);
  @override
  _i11.RequestState get state => (super.noSuchMethod(Invocation.getter(#state),
      returnValue: _i11.RequestState.Empty) as _i11.RequestState);
  @override
  _i9.TVSeasonsDetail get tvSeasons => (super.noSuchMethod(
          Invocation.getter(#tvSeasons),
          returnValue: _FakeTVSeasons_7(this, Invocation.getter(#tvSeasons)))
      as _i9.TVSeasonsDetail);
  @override
  String get message =>
      (super.noSuchMethod(Invocation.getter(#message), returnValue: '')
          as String);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  _i13.Future<void> fetchTVSeasonDetail(int? id, int? season) =>
      (super.noSuchMethod(Invocation.method(#fetchTVSeasonDetail, [id, season]),
              returnValue: _i13.Future<void>.value(),
              returnValueForMissingStub: _i13.Future<void>.value())
          as _i13.Future<void>);
  @override
  void addListener(_i14.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i14.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}

/// A class which mocks [NavigatorObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigatorObserver extends _i1.Mock implements _i16.NavigatorObserver {
  @override
  void didPush(
          _i16.Route<dynamic>? route, _i16.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(Invocation.method(#didPush, [route, previousRoute]),
          returnValueForMissingStub: null);
  @override
  void didPop(_i16.Route<dynamic>? route, _i16.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(Invocation.method(#didPop, [route, previousRoute]),
          returnValueForMissingStub: null);
  @override
  void didRemove(
          _i16.Route<dynamic>? route, _i16.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(Invocation.method(#didRemove, [route, previousRoute]),
          returnValueForMissingStub: null);
  @override
  void didReplace(
          {_i16.Route<dynamic>? newRoute, _i16.Route<dynamic>? oldRoute}) =>
      super.noSuchMethod(
          Invocation.method(
              #didReplace, [], {#newRoute: newRoute, #oldRoute: oldRoute}),
          returnValueForMissingStub: null);
  @override
  void didStartUserGesture(
          _i16.Route<dynamic>? route, _i16.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(
          Invocation.method(#didStartUserGesture, [route, previousRoute]),
          returnValueForMissingStub: null);
  @override
  void didStopUserGesture() =>
      super.noSuchMethod(Invocation.method(#didStopUserGesture, []),
          returnValueForMissingStub: null);
}
